"""create all tables

Revision ID: 2189f832c645
Revises: 
Create Date: 2026-09-06 07:28:22.634596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2189f832c645'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('max_webhook_logs',
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Тип события от MAX'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='Полный payload от MAX'),
    sa.Column('processed', sa.Boolean(), nullable=True, comment='Обработано ли событие'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='Время обработки'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_max_webhook_logs_id'), 'max_webhook_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Номер телефона'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='Полное имя'),
    sa.Column('role', sa.Enum('ADMIN', 'LOGIST', 'DRIVER', name='userrole'), nullable=False, comment='Роль в системе'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активен (не заблокирован)'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='В архиве (скрыт из списков)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('driver_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_user_id', sa.String(length=100), nullable=True, comment='ID пользователя в MAX'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='Подтверждён ли аккаунт MAX'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('max_user_id')
    )
    op.create_index(op.f('ix_driver_profiles_id'), 'driver_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_driver_profiles_user_id'), 'driver_profiles', ['user_id'], unique=True)
    op.create_table('trips',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('logist_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Дата рейса'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'CONFIRMED', 'PARTIAL', 'REJECTED', name='tripstatus'), nullable=False, comment='Статус рейса'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='Когда отправлено уведомление в MAX'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['logist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_date'), 'trips', ['date'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_logist_id'), 'trips', ['logist_id'], unique=False)
    op.create_table('routes',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False, comment='Порядковый номер в рейсе'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='routestatus'), nullable=False, comment='Статус маршрута'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Причина отказа (если отклонён)'),
    sa.Column('address_start', sa.String(length=255), nullable=False, comment='Адрес начала маршрута'),
    sa.Column('address_end', sa.String(length=255), nullable=False, comment='Адрес конца маршрута'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_trip_id'), 'routes', ['trip_id'], unique=False)
    op.create_table('points',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False, comment='Порядковый номер в маршруте'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='Адрес торговой точки'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='pointstatus'), nullable=False, comment='Статус точки'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Причина отказа (если отклонена)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_id'), 'points', ['id'], unique=False)
    op.create_index(op.f('ix_points_route_id'), 'points', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_route_id'), table_name='points')
    op.drop_index(op.f('ix_points_id'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_routes_trip_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_trips_logist_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_date'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_driver_profiles_user_id'), table_name='driver_profiles')
    op.drop_index(op.f('ix_driver_profiles_id'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_max_webhook_logs_id'), table_name='max_webhook_logs')
    op.drop_table('max_webhook_logs')
    # ### end Alembic commands ###
