"""add info to trip, name to route, weight to point

Revision ID: 2aa29bc05aba
Revises: bfcb2b925624
Create Date: 2026-09-13 08:01:21.830749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa29bc05aba'
down_revision: Union[str, None] = 'bfcb2b925624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True, comment='Вес товара, кг'))
    op.add_column('routes', sa.Column('name', sa.String(length=255), nullable=True, comment='Название маршрута (из 1С)'))
    op.add_column('trips', sa.Column('info', sa.String(length=300), nullable=True, comment='Произвольная информация'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'info')
    op.drop_column('routes', 'name')
    op.drop_column('points', 'weight')
    # ### end Alembic commands ###
