"""add rejection_reasons table

Revision ID: 57ec6f8bbb1d
Revises: 93ae0d59c7b6
Create Date: 2026-09-26 09:56:59.695261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ec6f8bbb1d'
down_revision: Union[str, None] = '93ae0d59c7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejection_reasons',
    sa.Column('scope', sa.Enum('TRIP', 'ROUTE', 'POINT', name='rejectionscope'), nullable=False, comment='Уровень отказа: рейс / маршрут / точка'),
    sa.Column('text', sa.String(length=255), nullable=False, comment='Текст причины (видит водитель и логист)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Мягкое удаление: False — причина скрыта из выбора'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejection_reasons_id'), 'rejection_reasons', ['id'], unique=False)
    op.create_index(op.f('ix_rejection_reasons_scope'), 'rejection_reasons', ['scope'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rejection_reasons_scope'), table_name='rejection_reasons')
    op.drop_index(op.f('ix_rejection_reasons_id'), table_name='rejection_reasons')
    op.drop_table('rejection_reasons')
    # ### end Alembic commands ###
