"""add code to user, make logist_id nullable

Revision ID: 5bebacc5ee17
Revises: 2aa29bc05aba
Create Date: 2026-09-18 08:37:48.547597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bebacc5ee17'
down_revision: Union[str, None] = '2aa29bc05aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'logist_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Логист')
    op.add_column('users', sa.Column('code', sa.String(length=10), nullable=True, comment='Код из 1С (справочник Физические лица)'))
    op.create_index(op.f('ix_users_code'), 'users', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_code'), table_name='users')
    op.drop_column('users', 'code')
    op.alter_column('trips', 'logist_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Логист')
    # ### end Alembic commands ###
