"""add logist_code to trip, code and date to point

Revision ID: 93ae0d59c7b6
Revises: 5bebacc5ee17
Create Date: 2026-09-18 12:41:59.242627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ae0d59c7b6'
down_revision: Union[str, None] = '5bebacc5ee17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('code', sa.String(length=10), nullable=False, comment='Код точки из 1С'))
    op.add_column('points', sa.Column('date', sa.Date(), nullable=False, comment='Дата отгрузки'))
    op.create_index(op.f('ix_points_code'), 'points', ['code'], unique=False)
    op.create_index(op.f('ix_points_date'), 'points', ['date'], unique=False)
    op.create_unique_constraint('uq_point_code_date', 'points', ['code', 'date'])
    op.add_column('trips', sa.Column('logist_code', sa.String(length=10), nullable=True, comment='Код логиста из 1С (справочник Пользователи)'))
    op.create_index(op.f('ix_trips_logist_code'), 'trips', ['logist_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_logist_code'), table_name='trips')
    op.drop_column('trips', 'logist_code')
    op.drop_constraint('uq_point_code_date', 'points', type_='unique')
    op.drop_index(op.f('ix_points_date'), table_name='points')
    op.drop_index(op.f('ix_points_code'), table_name='points')
    op.drop_column('points', 'date')
    op.drop_column('points', 'code')
    # ### end Alembic commands ###
