"""add_max_user_id_to_user

Revision ID: bfcb2b925624
Revises: 2189f832c645
Create Date: 2026-09-07 16:14:38.879098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfcb2b925624'
down_revision: Union[str, None] = '2189f832c645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID пользователя',
               existing_nullable=False)
    op.alter_column('driver_profiles', 'max_user_id',
               existing_type=sa.VARCHAR(length=100),
               comment='ID в MAX',
               existing_comment='ID пользователя в MAX',
               existing_nullable=True)
    op.alter_column('driver_profiles', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='Подтверждён в MAX',
               existing_comment='Подтверждён ли аккаунт MAX',
               existing_nullable=True)
    op.alter_column('max_webhook_logs', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Тип события',
               existing_comment='Тип события от MAX',
               existing_nullable=False)
    op.alter_column('max_webhook_logs', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Данные',
               existing_comment='Полный payload от MAX',
               existing_nullable=False)
    op.alter_column('max_webhook_logs', 'processed',
               existing_type=sa.BOOLEAN(),
               comment='Обработано',
               existing_comment='Обработано ли событие',
               existing_nullable=True)
    op.alter_column('points', 'route_id',
               existing_type=sa.INTEGER(),
               comment='Маршрут',
               existing_nullable=False)
    op.alter_column('points', 'order_number',
               existing_type=sa.INTEGER(),
               comment='Порядковый номер',
               existing_comment='Порядковый номер в маршруте',
               existing_nullable=False)
    op.alter_column('points', 'address',
               existing_type=sa.VARCHAR(length=255),
               comment='Адрес точки',
               existing_comment='Адрес торговой точки',
               existing_nullable=False)
    op.alter_column('points', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'REJECTED', name='pointstatus'),
               comment='Статус',
               existing_comment='Статус точки',
               existing_nullable=False)
    op.alter_column('points', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='Причина отказа',
               existing_comment='Причина отказа (если отклонена)',
               existing_nullable=True)
    op.alter_column('routes', 'trip_id',
               existing_type=sa.INTEGER(),
               comment='Рейс',
               existing_nullable=False)
    op.alter_column('routes', 'order_number',
               existing_type=sa.INTEGER(),
               comment='Порядковый номер',
               existing_comment='Порядковый номер в рейсе',
               existing_nullable=False)
    op.alter_column('routes', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'REJECTED', name='routestatus'),
               comment='Статус',
               existing_comment='Статус маршрута',
               existing_nullable=False)
    op.alter_column('routes', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='Причина отказа',
               existing_comment='Причина отказа (если отклонён)',
               existing_nullable=True)
    op.alter_column('routes', 'address_start',
               existing_type=sa.VARCHAR(length=255),
               comment='Адрес начала',
               existing_comment='Адрес начала маршрута',
               existing_nullable=False)
    op.alter_column('routes', 'address_end',
               existing_type=sa.VARCHAR(length=255),
               comment='Адрес конца',
               existing_comment='Адрес конца маршрута',
               existing_nullable=False)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.INTEGER(),
               comment='Водитель',
               existing_nullable=False)
    op.alter_column('trips', 'logist_id',
               existing_type=sa.INTEGER(),
               comment='Логист',
               existing_nullable=False)
    op.alter_column('trips', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'CONFIRMED', 'PARTIAL', 'REJECTED', name='tripstatus'),
               comment='Статус',
               existing_comment='Статус рейса',
               existing_nullable=False)
    op.alter_column('trips', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Отправлено в MAX',
               existing_comment='Когда отправлено уведомление в MAX',
               existing_nullable=True)
    op.add_column('users', sa.Column('max_user_id', sa.String(length=100), nullable=True, comment='ID пользователя в MAX'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'LOGIST', 'DRIVER', name='userrole'),
               comment='Роль',
               existing_comment='Роль в системе',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Активен',
               existing_comment='Активен (не заблокирован)',
               existing_nullable=True)
    op.alter_column('users', 'is_archived',
               existing_type=sa.BOOLEAN(),
               comment='В архиве',
               existing_comment='В архиве (скрыт из списков)',
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['max_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'is_archived',
               existing_type=sa.BOOLEAN(),
               comment='В архиве (скрыт из списков)',
               existing_comment='В архиве',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Активен (не заблокирован)',
               existing_comment='Активен',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'LOGIST', 'DRIVER', name='userrole'),
               comment='Роль в системе',
               existing_comment='Роль',
               existing_nullable=False)
    op.drop_column('users', 'max_user_id')
    op.alter_column('trips', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Когда отправлено уведомление в MAX',
               existing_comment='Отправлено в MAX',
               existing_nullable=True)
    op.alter_column('trips', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'CONFIRMED', 'PARTIAL', 'REJECTED', name='tripstatus'),
               comment='Статус рейса',
               existing_comment='Статус',
               existing_nullable=False)
    op.alter_column('trips', 'logist_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Логист',
               existing_nullable=False)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Водитель',
               existing_nullable=False)
    op.alter_column('routes', 'address_end',
               existing_type=sa.VARCHAR(length=255),
               comment='Адрес конца маршрута',
               existing_comment='Адрес конца',
               existing_nullable=False)
    op.alter_column('routes', 'address_start',
               existing_type=sa.VARCHAR(length=255),
               comment='Адрес начала маршрута',
               existing_comment='Адрес начала',
               existing_nullable=False)
    op.alter_column('routes', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='Причина отказа (если отклонён)',
               existing_comment='Причина отказа',
               existing_nullable=True)
    op.alter_column('routes', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'REJECTED', name='routestatus'),
               comment='Статус маршрута',
               existing_comment='Статус',
               existing_nullable=False)
    op.alter_column('routes', 'order_number',
               existing_type=sa.INTEGER(),
               comment='Порядковый номер в рейсе',
               existing_comment='Порядковый номер',
               existing_nullable=False)
    op.alter_column('routes', 'trip_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Рейс',
               existing_nullable=False)
    op.alter_column('points', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='Причина отказа (если отклонена)',
               existing_comment='Причина отказа',
               existing_nullable=True)
    op.alter_column('points', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'REJECTED', name='pointstatus'),
               comment='Статус точки',
               existing_comment='Статус',
               existing_nullable=False)
    op.alter_column('points', 'address',
               existing_type=sa.VARCHAR(length=255),
               comment='Адрес торговой точки',
               existing_comment='Адрес точки',
               existing_nullable=False)
    op.alter_column('points', 'order_number',
               existing_type=sa.INTEGER(),
               comment='Порядковый номер в маршруте',
               existing_comment='Порядковый номер',
               existing_nullable=False)
    op.alter_column('points', 'route_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Маршрут',
               existing_nullable=False)
    op.alter_column('max_webhook_logs', 'processed',
               existing_type=sa.BOOLEAN(),
               comment='Обработано ли событие',
               existing_comment='Обработано',
               existing_nullable=True)
    op.alter_column('max_webhook_logs', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Полный payload от MAX',
               existing_comment='Данные',
               existing_nullable=False)
    op.alter_column('max_webhook_logs', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Тип события от MAX',
               existing_comment='Тип события',
               existing_nullable=False)
    op.alter_column('driver_profiles', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='Подтверждён ли аккаунт MAX',
               existing_comment='Подтверждён в MAX',
               existing_nullable=True)
    op.alter_column('driver_profiles', 'max_user_id',
               existing_type=sa.VARCHAR(length=100),
               comment='ID пользователя в MAX',
               existing_comment='ID в MAX',
               existing_nullable=True)
    op.alter_column('driver_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###
