"""drop address_start/address_end from routes

Revision ID: e074509c7497
Revises: 57ec6f8bbb1d
Create Date: 2026-10-04 04:40:01.105856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e074509c7497'
down_revision: Union[str, None] = '57ec6f8bbb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'address_start')
    op.drop_column('routes', 'address_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('address_end', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Адрес конца'))
    op.add_column('routes', sa.Column('address_start', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Адрес начала'))
    # ### end Alembic commands ###
